import type { ImportContract } from "./importContract.js";

export const exampleProject: ImportContract = {
  external_id: "BT-job-1042",
  external_source: "buildertrend",
  project: {
    name: "Henderson Residence",
    address: "812 Oak Ridge Dr, Boise, ID",
  },
  rooms: [
    {
      room_name: "Master Bath",
      entries: [
        {
          trade: "tile",
          brand: "Daltile",
          style: "Marble Attache",
          color: "Lavish White",
          sku: "MA85",
          grout_color: "Delorean Gray",
          grout_sku: "MAPEI-103",
          edge_profile: "bullnose",
          pattern: "stacked",
          location_in_room: "shower_walls",
          notes: "12x24 large format, vertical orientation",
          allowance: 18.0,
        },
        {
          trade: "tile",
          brand: "MSI",
          style: "Carrara Bianco",
          color: "White",
          sku: "NCAR2X2HEX",
          grout_color: "Delorean Gray",
          grout_sku: "MAPEI-103",
          edge_profile: "none",
          pattern: "set straight",
          location_in_room: "floor",
          notes: "2x2 hex, polished",
        },
        {
          trade: "paint",
          brand: "Sherwin-Williams",
          color_name: "Alabaster",
          sku: "SW7008",
          sheen: "matte",
          surface_application: "walls",
        },
        {
          trade: "paint",
          brand: "Sherwin-Williams",
          color_name: "Pure White",
          sku: "SW7005",
          sheen: "semi-gloss",
          surface_application: "trim",
        },
        {
          trade: "countertop",
          material: "quartz",
          brand: "Cambria",
          color: "Brittanicca",
          edge_profile: "eased",
          notes: "vanity top",
        },
        {
          trade: "cabinet",
          brand: "Showplace",
          style: "Pendleton",
          color: "Maple - White Icing",
          hardware: "Top Knobs Asbury 3-1/2 in. matte black",
        },
      ],
    },
    {
      room_name: "Kitchen",
      entries: [
        {
          trade: "tile",
          brand: "Schluter",
          style: "Subway",
          color: "White",
          sku: "BWHITE3X12",
          grout_color: "Snow White",
          grout_sku: "MAPEI-38",
          edge_profile: "bullnose",
          pattern: "staggered horizontal",
          location_in_room: "backsplash",
          notes: "3x12 ceramic subway, 1/3 offset",
        },
        {
          trade: "hardwood",
          brand: "DuChateau",
          species: "European White Oak",
          color: "Vernal",
          sku: "DCH-VER-7.5",
          plank_width: "7.5 in",
          pattern: "set straight",
        },
        {
          trade: "paint",
          brand: "Sherwin-Williams",
          color_name: "Alabaster",
          sku: "SW7008",
          sheen: "matte",
          surface_application: "walls",
        },
        {
          trade: "cabinet",
          brand: "Showplace",
          style: "Covington",
          color: "Painted - Sea Salt",
          hardware: "Emtek Bristol satin brass pulls",
        },
        {
          trade: "countertop",
          material: "quartzite",
          brand: "Polycor",
          color: "Taj Mahal",
          edge_profile: "mitered 2 in",
        },
      ],
    },
  ],
};
